--UNIT_2 Relational Query Language

--Firsty SQL is divided into $ categories DDL(data definition language), DML(data manipulation language), DCL(data control language) and TCL(transaction control language)
--DDL has Create, drop, Alter, TRuncate, Rename.
--DML has Insert, Update, Delete, Select
--TCL has Commit, Rollback, Savepoint
--DCL has Grant, Revoke.

--Syntax for role
create role role_name;
--Syntax for creating table and using default value for a column
create table table_name(
    column_name data_type constraint,
    column_name data_type constraint default default_value,
    column_name data_type constraint,
    ...
);

--We will now be talking about serial data type which is used for auto incrementing primary key
--Syntax for serial data type
create table table_name(
    id serial primary key,
    column_name data_type constraint,
    column_name data_type constraint default default_value,
    column_name data_type constraint,
    ...
);

--We will now be moving on to Identity data type which is used for auto incrementing primary key and it is more flexible than serial data type
--Syntax for identity data type
create table table_name(
    id int generated always as identity primary key,
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    column_name data_type constraint,
    column_name data_type constraint default default_value,
    column_name data_type constraint,
    ...
);

--Syntax for creating table with foreign key
create table table_name(
    id serial primary key,
    column_name data_type constraint,
    column_name data_type constraint default default_value,
    column_name data_type constraint,
    foreign key (foreign_key_column) references parent_table(parent_column),
    --or we can also write it like this in case of multiple foreign keys
    foregin key (colunm1, comumn2) references parent_table(parent_column1, parent_column2),
    --or just to define composite foreign key without referencing parent table
    foreign key (column1, column2)
    ...
);

--Syntax for dropping table
drop table table_name;

--Different use cases and syntac for Alter table.
--Adding a column
alter table table_name add column column_name data_type constraint;
--Dropping a column
alter table table_name drop column column_name;
--Modifying a column data type
alter table table_name alter column column_name type new_data_type;
--Renaming a column
alter table table_name rename column old_column_name to new_column_name;
--Renaming a table
alter table old_table_name rename to new_table_name;
--Adding a constraint
alter table table_name add constraint constraint_name constraint_type (column_name);
--Dropping a constraint
alter table table_name drop constraint constraint_name;
--in case of adding multipe columns
alter table table_name add column column_name1 data_type constraint, add column column_name2 data_type constraint, ...;
--in case of dropping multiple columns
alter table table_name drop column column_name1, drop column column_name2, ...;
--in case of modifying multiple columns data type or adding multiple data type or even dropping multiple constraints
alter table table_name alter column column_name1 type new_data_type, alter column column_name2 type new_data_type, ...;
--in case of renaming multiple columns or tables
alter table old_table_name rename to new_table_name, rename column old_column_name1 to new_column_name1, rename column old_column_name2 to new_column_name2, ...;

--Noe talking about the identity function which is used to generate unique values for a column
--Syntax for identity function
coulmn_name data_type generate {always | by default} as identity (START WITH start_value, INCREMENT BY increment_value) constraint;
--the  start with value can only be specified in case of using by default which is also optional.
--incase its deleted it will start with 1 and increment by 1 by default if no start with and increment by value is specified.

--now moving on to resest identity which is used to reset the identity column value
--Syntax for reset identity
alter table table_name alter column column_name restart with new_start_value;

--now we will be  talking about the truncate table which is used to delete all the rows from a table and reset the identity coloum value
--Syntax for truncate table
truncate table table_name restart identity;
--or if you just want to delete all the rows without resetting the identity column value
truncate table table_name;

--moving on to the delete statement which is used to delete specific rows from a table based on a condition
--Syntax for delete statement
delete from table_name where condition;

-- while we are at it lets also talk about comments on table we all know how to do comments on the query which is -- for single line and /* */ for multi line but we can also add comments on table and column which is very useful for documentation purpose
--Syntax for adding comments on table and column
comment on table table_name is 'This is a comment on the table';
comment on column table_name.column_name is 'This is a comment on the column';

-- now lets talk about order by clause which is used to sort the result set in ascending or descending order
--Syntax for order by clause
select column_name1, column_name2, ... from table_name order by {acs|desc};
--we can also sort by multiple columns  
select column_name1, column_name2, ... from table_name order by column_name1 {asc|desc}, column_name2 {asc|desc}, ...;

-- where and insert into clause
--Syntax for where clause
select column_name1, column_name2, ... from table_name where condition;
--Syntax for insert into clause
insert into table_name (column_name1, column_name2, ...) values (value1, value2, ...);
--we can also insert multiple rows at once
insert into table_name (column_name1, column_name2, ...) values (value1, value2, ...), (value1, value2, ...), ...;
-- or we can also insert data directly from a different row using select statement
insert into table_name (column_name1, column_name2, ...) select column_name1, column_name2, ... from another_table where condition;

-- let us talk about the upsert clause now which is suppose to do an action when there is a conflict with the primary key or unique constraint
--Syntax for upsert clause
insert into table_name (column_name1, column_name2, ...) values (value1, value2, ...)
on conflict (column_name) do {nothing | update set column_name1 = value1, column_name2 = value2, ... where condition};
--insert with Exclude constraint
insert into table_name (column_name1, column_name2, ...) values (value1, value2, ...)
on conflict on constraint constraint_name do update set  column_name = excluded.column_name where condition;

--now let do as clause which is used to give an alias to a table or column name
--Syntax for as clause
select column_name as alias_name from table_name;
--we can also give alias to table name
select column_name from table_name as alias_name;
--we can also give alias to both table and column name
select column_name as alias_name from table_name as alias_name;

--Examples of contraints (primary key, foreign key, unique, not null, check, default)
--Data integrity constraints are used to ensure the accuracy and consistency of data in a database. (cascade, set null, set default, restrict, no action)
--They are rules that are applied to the columns of a table to restrict the type of data that can be inserted into the table. Here are some examples of constraints:
--Primary Key Constraint: This constraint is used to uniquely identify each record in a table. It ensures that the values in the primary key column are unique and not null.
create table employees (
    employee_id serial primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) unique,
    salary numeric check (salary > 0),
    department_id int default 1
);

alter table table_name drop constraint contraint_name;
alter table table_name add constraint constraint_name primary key (column_name);
alter table table_name drop constraint constraint_name primary key (column_name);

-- let talk about cascade, set null, set default, Restrict, no action
--Cascade: When a record in the parent table is deleted or updated, the corresponding records in the child table are also deleted or updated.
--Set Null: When a record in the parent table is deleted or updated, the corresponding foreign key values in the child table are set to null.
--Set Default: When a record in the parent table is deleted or updated, the corresponding foreign key values in the child table are set to their default values.
--Restrict: When a record in the parent table is deleted or updated, the corresponding records in the child table are not deleted or updated, and an error is raised.
--No Action: When a record in the parent table is deleted or updated, the corresponding records in the child table are not deleted or updated, and no error is raised.

--syntax for set null
create table parent_table (
    id serial primary key,
    name varchar(50) not null
);
-- now for cascade
create table child_table (
    id serial primary key,
    parent_id int,
    name varchar(50) not null,
    foreign key (parent_id) references parent_table(id) on delete cascade on update cascade
);

--syntax for set null
create table child_table (
    id serial primary key,
    parent_id int,
    name varchar(50) not null,
    foreign key (parent_id) references parent_table(id) on delete set null on update set null
);
--syntax for set default
create table child_table (
    id serial primary key,
    parent_id int,
    name varchar(50) not null,
    foreign key (parent_id) references parent_table(id) on delete set default on update set default
);
--syntax for restrict
create table child_table (
    id serial primary key,
    parent_id int,
    name varchar(50) not null,
    foreign key (parent_id) references parent_table(id) on delete restrict on update restrict
);
--syntax for no action
create table child_table (
    id serial primary key,
    parent_id int,
    name varchar(50) not null,
    foreign key (parent_id) references parent_table(id) on delete no action on update no action
);

--now for check constraint which is used to ensure that the values in a column meet a specific condition
--Syntax for check constraint
create table employees (
    employee_id serial primary key,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    email varchar(100) unique,
    salary numeric check (salary > 0),
    department_id int default 1
);

-- operators in sql are as follows (=, <>, >, <, >=, <=, AND, OR, NOT, IN, BETWEEN, LIKE, IS NULL, IS NOT NULL)
select  product, quantity * unit_price as total_price from sales where quantity > 10 and unit_price < 100;

-- a relational operrators return a true, false or a null value.

--like operator is used to search for a specific pattern in a column
--Syntax for like operator
select column_name from table_name where column_name like 'pattern';
-- the pattern can be defined using % and _ wildcards. % represents zero or more characters, while _ represents a single character.
--Example of like operator
select first_name from employees where first_name like 'J%'; -- this will return all the first names that start with J

--example of AND, OR, NOT, IN, BETWEEN, NOT IN
select * from employees where salary > 50000 and department_id = 1; -- this will return all the employees who have a salary greater than 50000 and belong to department 1
select * from employees where salary > 50000 or department_id = 1; -- this will return all the employees who have a salary greater than 50000 or belong to department 1
select * from employees where not (salary > 50000); -- this will return all the employees who do not have a salary greater than 50000
select * from employees where department_id in (1, 2, 3); -- this will return all the employees who belong to department 1, 2 or 3
select * from employees where salary between 50000 and 100000; -- this will return all the employees who have a salary between 50000 and 100000
select * from employees where department_id not in (1, 2, 3); -- this will return all the employees who do not belong to department 1, 2 or 3

--limit and offset clause
--Syntax for limit and offset clause
select column_name from table_name limit number_of_rows offset number_of_rows;
--Example of limit and offset clause
select * from employees limit 5; -- this will return the first 5 rows from the employees table
select * from employees offset 5; -- this will return all the rows from the employees table except the first 5 rows
select * from employees limit 5 offset 5; -- this will return 5 rows from the employees table starting from the 6th row

-- fetch clause is used to retrieve a specific number of rows from a result set
--Syntax for fetch clause  
select column_name from table_name fetch first number_of_rows rows only;
--Example of fetch clause
select * from employees fetch first 5 rows only; -- this will return the first 5

-- subqueries are used to retrieve data from one table based on the data from another table
--Syntax for subquery   
select column_name from table_name where column_name operator (select column_name from another_table where condition);
--Example of subquery  
select first_name from employees where department_id = (select department_id from departments where department_name = 'Sales'); 
-- this will return the first names of all the employees who belong to the Sales department

--subquery with exists operator( what this does is it checks if the subquery returns any rows or not if it returns then it will return true otherwise false)
select column_name from table_name where exists (select column_name from another_table where condition);

-- built in queries like ceil, floor, round, abs, sqrt, mod, now, concat, upper, lower, ascii, substring, count, sum, avg, min, max
-- extract, exp, ln, power(number, power), trim, translate.

--(translate is used to replace a specific character in a string with another character)

-- grante and revoke statements are used to give and take away permissions from a user or role
--Syntax for grant statement
grant permission_type on object_name to role_name;
--Example of grant statement
grant select on employees to user_name; -- this will give select permission on employees table to user_name
grant all on employees to user_name; -- this will give all permissions on employees table to user_name
--Syntax for revoke statement
revoke permission_type on object_name from role_name;
--Example of revoke statement
revoke select on employees from user_name; -- this will take away select permission on employees table from user_name
revoke all on employees from user_name; -- this will take away all permissions on employees table from user_name


-- now we do begin, commit, rollback, savepoint statements which are used to manage transactions in a database
--Syntax for begin statement
begin;
--Syntax for commit statement
commit;
--Syntax for rollback statement
rollback;
--Syntax for savepoint statement
savepoint savepoint_name;
-- or we can also use savepoint without giving a name to it and use rollback to savepoint to rollback to the last savepoint
savepoint;
rollback to savepoint; -- this will rollback to the last savepoint

